# Generated by Django 2.2.4 on 2019-08-24 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crust',
            fields=[
                ('crustId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoiceId', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pizza.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('sauceId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('toppingId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('pizzaId', models.AutoField(primary_key=True, serialize=False)),
                ('discount', models.FloatField()),
                ('crust', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pizza.Crust')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pizza.Invoice')),
                ('sauce', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pizza.Sauce')),
                ('toppings', models.ManyToManyField(to='pizza.Topping')),
            ],
        ),
    ]
